import { Poppins } from "next/font/google"

import StyledComponentsRegistry from "./registry"
import AppLayout from "./layouts/AppLayout/AppLayout"
import Providers from "./providers"

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <StyledComponentsRegistry>
          <Providers>
            <AppLayout>{children}</AppLayout>
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
